---
repos:
  -
    repo: 'https://github.com/pre-commit/pre-commit-hooks.git'
    rev: v2.1.0
    hooks:
      -
        id: trailing-whitespace
        stages:
          - commit
          - push
      -
        id: check-json
        stages:
          - commit
          - push
      -
        id: flake8
        stages:
          - commit
          - push
        exclude: ^bootstrap.py$
      -
        id: check-yaml
        stages:
          - commit
          - push
      -
        id: check-json
        stages:
          - commit
          - push
      -
        id: check-merge-conflict
        stages:
          - commit
          - push
      -
        id: debug-statements
        stages:
          - commit
          - push
      -
        id: fix-encoding-pragma
        stages:
          - commit
          - push
      -
        id: check-symlinks
        stages:
          - commit
          - push
      -
        id: debug-statements
        stages:
          - commit
          - push
  -
    repo: 'https://github.com/jumanjihouse/pre-commit-hooks.git'
    rev: 1.11.0
    hooks:
      -
        id: shellcheck
        stages:
          - commit
          - push
      -
        id: shfmt
        stages:
          - commit
          - push
  -
    repo: 'https://github.com/asottile/yesqa'
    rev: v0.0.10
    hooks:
      -
        id: yesqa
        stages:
          - commit
          - push
  -
    repo: 'https://github.com/adrienverge/yamllint'
    rev: v1.15.0
    hooks:
      -
        id: yamllint
        stages:
          - commit
          - push
  -
    repo: 'https://github.com/jorisroovers/gitlint.git'
    rev: v0.11.0
    hooks:
      -
        id: gitlint
        stages:
          - commit-msg
  - repo: 'git://github.com/luismayta/pre-commit-isort'
    rev: 1.0.1
    hooks:
      - id: isort
        name: isort
        args:
          - -y
        language_version: python
        types: [python]
  - repo: 'https://github.com/ambv/black.git'
    rev: a4399f3054206eac52a89832a415e31077bafa0a
    hooks:
      - id: black
        name: black
        description: 'Black: The uncompromising Python code formatter'
        entry: black
        language: python
        language_version: python3
        require_serial: true
        types: [python]
        exclude: ^bootstrap.py$
  -
    repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.700
    hooks:
      - id: mypy
#  - repo: local
#    hooks:
#      - id: run-tests
#        name: Running unit tests
#        entry: pytest
#        pass_filenames: false
#        language: system
#        stages: [commit, push]
