---
language: nix

before_install:
  - sudo mkdir -p /etc/nix
  - echo "binary-caches = https://cache.nixos.org https://imio.cachix.org" | sudo tee -a /etc/nix/nix.conf > /dev/null
  - echo "binary-cache-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= imio.cachix.org-1:XRqcHQyUgbqq02ojDg0gdkEdHp63n5yINhBC55mPRKI=" | sudo tee -a /etc/nix/nix.conf > /dev/null

script:
  - nix-env -iA cachix -f https://cachix.org/api/v1/install
  - cachix use imio
  - nix-shell --pure --run "SOURCE_DATE_EPOCH=315532800 pre-commit run --all"
